In [1]:
import tensorflow as tf
import keras
from keras.layers import Dense, Conv2D, MaxPool2D
from keras.models import Sequential
import tensorflow_datasets as tfds

In [2]:
mnist_train, info = tfds.load('fashion_mnist', split='train', with_info=True)
info

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_path='/Users/samin/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      aut

In [3]:
for item in mnist_train.take(1):
    print(type(item))       # input_shape=(28,28,1))
    print(item.keys())      # tf.Tensor([[pixel values]])
    print(item['image'])       # shape=(28, 28, 1), dtype=uint8)
    print(item['label'])       #  tf.Tensor(2, shape=(), dtype=int64)

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


2023-06-25 22:00:34.366349: W tensorflow/core/kernels/data/cache_dataset_ops.cc:854] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [4]:
# CNN model
(training_images, training_labels), (test_images, test_labels) =  tfds.as_numpy(tfds.load('fashion_mnist',
                                                                    split = ['train', 'test'],
                                                                    batch_size=-1,
                                                                    as_supervised=True))

# normalize
training_images = training_images / 255.0
test_images = test_images / 255.0

# create model
model = tf.keras.models.Sequential([
            tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu', 
                input_shape=(28, 28, 1), padding='same'),
            tf.keras.layers.MaxPooling2D(2, 2),
            tf.keras.layers.Conv2D(64, (3, 3), activation='relu', 
                padding='same'),
            tf.keras.layers.MaxPooling2D(2,2),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(128, activation=tf.nn.relu),
            tf.keras.layers.Dense(10, activation='softmax')
 ])
model.compile(optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=10, validation_split=0.2)

Epoch 1/10
1500/1500 [==============================] - 22s 15ms/step - loss: 0.4200 - accuracy: 0.8504 - val_loss: 0.3041 - val_accuracy: 0.8891
Epoch 2/10
1500/1500 [==============================] - 20s 13ms/step - loss: 0.2721 - accuracy: 0.9012 - val_loss: 0.2566 - val_accuracy: 0.9054
Epoch 3/10
1500/1500 [==============================] - 20s 13ms/step - loss: 0.2256 - accuracy: 0.9161 - val_loss: 0.2251 - val_accuracy: 0.9184
Epoch 4/10
1500/1500 [==============================] - 19s 13ms/step - loss: 0.1913 - accuracy: 0.9289 - val_loss: 0.2308 - val_accuracy: 0.9155
Epoch 5/10
1500/1500 [==============================] - 19s 13ms/step - loss: 0.1639 - accuracy: 0.9385 - val_loss: 0.2193 - val_accuracy: 0.9231
Epoch 6/10
1500/1500 [==============================] - 19s 13ms/step - loss: 0.1378 - accuracy: 0.9490 - val_loss: 0.2106 - val_accuracy: 0.9260
Epoch 7/10
1500/1500 [==============================] - 19s 13ms/step - loss: 0.1141 - accuracy: 0.9561 - val_loss: 0.2125 -

In [5]:
(training_images, training_labels), (test_images, test_labels) = tfds.as_numpy(tfds.load('fashion_mnist', split=['train','test'],
                                                                               batch_size=-1, as_supervised=True))

# Normalize
training_images = training_images/255.0
test_images = test_images/255.0

# Create the model (no CNNs)
model2 = keras.models.Sequential([
    keras.layers.Flatten(input_shape=(28,28,1)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(10, activation='softmax')]
)

model.compile(optimizer='adam',
 loss='sparse_categorical_crossentropy',
 metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=10, verbose=1, validation_split=0.2)

Epoch 1/10
1500/1500 [==============================] - 20s 13ms/step - loss: 0.0576 - accuracy: 0.9783 - val_loss: 0.2866 - val_accuracy: 0.9208
Epoch 2/10
1500/1500 [==============================] - 20s 13ms/step - loss: 0.0466 - accuracy: 0.9829 - val_loss: 0.3060 - val_accuracy: 0.9251
Epoch 3/10
1500/1500 [==============================] - 20s 14ms/step - loss: 0.0362 - accuracy: 0.9871 - val_loss: 0.3467 - val_accuracy: 0.9249
Epoch 4/10
1500/1500 [==============================] - 20s 13ms/step - loss: 0.0379 - accuracy: 0.9864 - val_loss: 0.3314 - val_accuracy: 0.9236
Epoch 5/10
1500/1500 [==============================] - 20s 13ms/step - loss: 0.0288 - accuracy: 0.9895 - val_loss: 0.4023 - val_accuracy: 0.9221
Epoch 6/10
1500/1500 [==============================] - 21s 14ms/step - loss: 0.0318 - accuracy: 0.9883 - val_loss: 0.3894 - val_accuracy: 0.9200
Epoch 7/10
1500/1500 [==============================] - 21s 14ms/step - loss: 0.0239 - accuracy: 0.9915 - val_loss: 0.4211 -